spring:
  redis:
    host: localhost
mail:
  accounts:
    - id: 100
      # 邮件服务器的SMTP地址
      host: smtp.qq.com
      # 邮件服务器的SMTP端口
      port: 465
      # 发件人（必须正确，否则发送失败）
      from: 554343346@qq.com
      # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
      username: 554343346@qq.com
      # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
      password: kchmklpqjpjvbcgg

#logging:
#  level:
#    root: debug